name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: ci
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: 1.x
