name: ci

on: [push, pull_request]
env:
  NO_COLOR: yes

jobs:
  build:
    runs-on: ubuntu-latest
    name: ci
    steps:
      - uses: actions/checkout@v2

      - uses: denoland/setup-deno@main
        with:
          deno-version: 1.x

      # - name: Test
      #   run: deno test --config tsconfig.json extension.ts

      - run: deno fmt

      - name: Bundle
        run: deno bundle --config tsconfig.json extension.ts extension.js

      # --no-check: https://github.com/octokit/octokit.js/issues/2075#issuecomment-830350826
      - name: Run deno install
        run: |
          DENO_INSTALL_ROOT=$PWD/bin
          echo DENO_INSTALL_ROOT="$DENO_INSTALL_ROOT" >> $GITHUB_ENV
          echo "$DENO_INSTALL_ROOT" >> $GITHUB_PATH
          deno install --no-check --location $GITHUB_API_URL --allow-env --allow-net --unstable release.ts

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            extension.js
